-- ═══════════════════════════════════════════════════════════════
--  NRITYA KALA MANDIR — Migration / Change Scripts
--  Run these ONLY when you need to update the database later.
--  DO NOT run the full script again — use these individual blocks.
-- ═══════════════════════════════════════════════════════════════

USE NrityaKalaMandir;
GO

-- ── HOW TO USE ────────────────────────────────────────────────
-- Select only the block you need and press F5 to run it.
-- Each block is safe to run multiple times (idempotent).
-- ─────────────────────────────────────────────────────────────

-- ────────────────────────────────────────
-- Change admin password
-- Replace 'YourNewBcryptHashHere' with the
-- hash generated by the Python script below
-- ────────────────────────────────────────
/*
UPDATE AdminUsers
SET PasswordHash = '$2b$12$YourNewBcryptHashHere'
WHERE Username = 'admin';
*/

-- ────────────────────────────────────────
-- Add a new admin user
-- ────────────────────────────────────────
/*
INSERT INTO AdminUsers (Username, PasswordHash, Email, IsActive)
VALUES ('manager', '$2b$12$YourHashHere', 'manager@yourdomain.com', 1);
*/

-- ────────────────────────────────────────
-- Deactivate a class without deleting it
-- ────────────────────────────────────────
/*
UPDATE DanceClasses SET IsActive = 0 WHERE Name = 'Odissi';
*/

-- ────────────────────────────────────────
-- Reorder gallery items
-- ────────────────────────────────────────
/*
UPDATE Gallery SET SortOrder = 1 WHERE Id = 5;
UPDATE Gallery SET SortOrder = 2 WHERE Id = 3;
-- etc.
*/

-- ────────────────────────────────────────
-- Mark all enquiries as read
-- ────────────────────────────────────────
/*
UPDATE Enquiries SET IsRead = 1 WHERE IsRead = 0;
*/

-- ────────────────────────────────────────
-- Export all enquiries to check
-- ────────────────────────────────────────
/*
SELECT
    Id,
    FirstName + ' ' + LastName AS FullName,
    Email, Phone, DanceForm,
    Message,
    CASE WHEN IsRead = 1 THEN 'Read' ELSE 'NEW' END AS Status,
    FORMAT(CreatedAt, 'dd-MMM-yyyy HH:mm') AS ReceivedOn
FROM Enquiries
ORDER BY CreatedAt DESC;
*/

-- ────────────────────────────────────────
-- Update event status to 'past' after the date passes
-- Run this periodically (or automate with SQL Agent Job)
-- ────────────────────────────────────────
/*
UPDATE Events
SET Status = 'past', UpdatedAt = GETUTCDATE()
WHERE EventDate < CAST(GETDATE() AS DATE)
  AND Status = 'upcoming';
*/

-- ────────────────────────────────────────
-- Clean expired auth tokens (run weekly)
-- ────────────────────────────────────────
/*
DELETE FROM AuthTokens WHERE ExpiresAt < GETUTCDATE();
*/

-- ────────────────────────────────────────
-- Add a new column (example: add Phone2 to Enquiries)
-- ────────────────────────────────────────
/*
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('Enquiries') AND name = 'Phone2'
)
    ALTER TABLE Enquiries ADD Phone2 NVARCHAR(30) NULL;
*/
